image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  ALPINE_VERSION: "3.10"
  AWSCLI_VERSION: "1.16.218"
  HUGO_VERSION: "0.56.3"
  TERRAGRUNT_VERSION: "0.19.19"

build-awscli:
  variables:
    PYTHON_VERSION: "3.7.4"
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg PYTHON_VERSION=${PYTHON_VERSION} --build-arg AWSCLI_VERSION=${AWSCLI_VERSION} -t $CI_REGISTRY/twaluigi/ci-images/awscli:${AWSCLI_VERSION} awscli/
    - docker tag $CI_REGISTRY/twaluigi/ci-images/awscli:${AWSCLI_VERSION} $CI_REGISTRY/twaluigi/ci-images/awscli:latest
    - docker push $CI_REGISTRY/twaluigi/ci-images/awscli:${AWSCLI_VERSION}
    - docker push $CI_REGISTRY/twaluigi/ci-images/awscli:latest

build-hugo:
  variables:
    HUGO_VERSION: "0.56.3"
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg ALPINE_VERSION=${ALPINE_VERSION} --build-arg HUGO_VERSION=${HUGO_VERSION} -t $CI_REGISTRY/twaluigi/ci-images/hugo:${HUGO_VERSION} hugo/
    - docker tag $CI_REGISTRY/twaluigi/ci-images/hugo:${HUGO_VERSION} $CI_REGISTRY/twaluigi/ci-images/hugo:latest
    - docker push $CI_REGISTRY/twaluigi/ci-images/hugo:${HUGO_VERSION}
    - docker push $CI_REGISTRY/twaluigi/ci-images/hugo:latest

build-terragrunt:
  variables:
    TERRAFORM_VERSION: "0.12.6"
    TERRAGRUNT_VERSION: "0.19.19"
    TERRAGRUNT_TFPATH: "/bin/terraform"
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg ALPINE_VERSION=${ALPINE_VERSION} --build-arg TERRAFORM_VERSION=${TERRAFORM_VERSION} --build-arg TERRAGRUNT_VERSION=${TERRAGRUNT_VERSION} --build-arg TERRAGRUNT_TFPATH=${TERRAGRUNT_TFPATH} -t $CI_REGISTRY/twaluigi/ci-images/terragrunt:${TERRAGRUNT_VERSION} terragrunt/
    - docker tag $CI_REGISTRY/twaluigi/ci-images/terragrunt:${TERRAGRUNT_VERSION} $CI_REGISTRY/twaluigi/ci-images/terragrunt:latest
    - docker push $CI_REGISTRY/twaluigi/ci-images/terragrunt:${TERRAGRUNT_VERSION}
    - docker push $CI_REGISTRY/twaluigi/ci-images/terragrunt:latest

push-awscli:
  stage: push
  before_script:
    - echo ${DOCKER_PASSWORD} | docker login -u $DOCKER_USERNAME --password-stdin
  script:
    - docker pull $CI_REGISTRY/twaluigi/ci-images/awscli:${AWSCLI_VERSION}
    - docker pull  $CI_REGISTRY/twaluigi/ci-images/awscli:latest
    - docker tag $CI_REGISTRY/twaluigi/ci-images/awscli:${AWSCLI_VERSION} $DOCKER_USERNAME/awscli:${AWSCLI_VERSION}
    - docker tag $CI_REGISTRY/twaluigi/ci-images/awscli:latest $DOCKER_USERNAME/awscli:latest
    - docker push $DOCKER_USERNAME/awscli:${AWSCLI_VERSION}
    - docker push $DOCKER_USERNAME/awscli:latest

push-hugo:
  stage: push
  before_script:
    - echo ${DOCKER_PASSWORD} | docker login -u $DOCKER_USERNAME --password-stdin
  script:
    - docker pull $CI_REGISTRY/twaluigi/ci-images/hugo:${HUGO_VERSION}
    - docker pull  $CI_REGISTRY/twaluigi/ci-images/hugo:latest
    - docker tag $CI_REGISTRY/twaluigi/ci-images/hugo:${HUGO_VERSION} $DOCKER_USERNAME/hugo:${HUGO_VERSION}
    - docker tag $CI_REGISTRY/twaluigi/ci-images/hugo:latest $DOCKER_USERNAME/hugo:latest
    - docker push $DOCKER_USERNAME/hugo:${HUGO_VERSION}
    - docker push $DOCKER_USERNAME/hugo:latest

push-terragrunt:
  stage: push
  before_script:
    - echo ${DOCKER_PASSWORD} | docker login -u $DOCKER_USERNAME --password-stdin
  script:
    - docker pull $CI_REGISTRY/twaluigi/ci-images/terragrunt:${TERRAGRUNT_VERSION}
    - docker pull  $CI_REGISTRY/twaluigi/ci-images/terragrunt:latest
    - docker tag $CI_REGISTRY/twaluigi/ci-images/terragrunt:${TERRAGRUNT_VERSION} $DOCKER_USERNAME/terragrunt:${TERRAGRUNT_VERSION}
    - docker tag $CI_REGISTRY/twaluigi/ci-images/terragrunt:latest $DOCKER_USERNAME/terragrunt:latest
    - docker push $DOCKER_USERNAME/terragrunt:${TERRAGRUNT_VERSION}
    - docker push $DOCKER_USERNAME/terragrunt:latest