image: docker:latest

services:
  - docker:dind

stages:
  - build

awscli:
  variables:
    PYTHON_VERSION: "3.7.4"
    AWSCLI_VERSION: "1.16.218"
  stage: build
  script:
    - docker build --build-arg PYTHON_VERSION=${PYTHON_VERSION} --build-arg AWSCLI_VERSION=${AWSCLI_VERSION} -t registry.gitlab.com/twaluigi/ci-images/awscli:${AWSCLI_VERSION} awscli/
    - docker build --build-arg PYTHON_VERSION=${PYTHON_VERSION} --build-arg AWSCLI_VERSION=${AWSCLI_VERSION} -t registry.gitlab.com/twaluigi/ci-images/awscli:latest awscli/