image: docker:latest

services:
  - docker:dind

stages:
  - build

awscli:
  variables:
    PYTHON_VERSION: "3.7.4"
    AWSCLI_VERSION: "1.16.218"
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg PYTHON_VERSION=${PYTHON_VERSION} --build-arg AWSCLI_VERSION=${AWSCLI_VERSION} -t $CI_REGISTRY/twaluigi/ci-images/awscli:${AWSCLI_VERSION} awscli/
    - docker build --build-arg PYTHON_VERSION=${PYTHON_VERSION} --build-arg AWSCLI_VERSION=${AWSCLI_VERSION} -t $CI_REGISTRY/twaluigi/ci-images/awscli:latest awscli/
    - docker push $CI_REGISTRY/twaluigi/ci-images/awscli:${AWSCLI_VERSION}
    - docker push $CI_REGISTRY/twaluigi/ci-images/awscli:latest